version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventory-db-prod
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    # Environment variables are now read from the .env file by the backend
    env_file:
      - ./backend/.env
    networks:
      - inventory-network-prod

  redis:
    image: redis:7-alpine
    container_name: inventory-redis-prod
    networks:
      - inventory-network-prod

  backend:
    build: ./backend
    container_name: inventory-backend-prod
    env_file:
      - ./backend/.env
    depends_on:
      - db
      - redis
    networks:
      - inventory-network-prod
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - HOME=/home/appuser
      - APP_HOME=/home/appuser/web
      - PYTHONPATH=${PYTHONPATH}:${APP_HOME}

  worker:
    build: ./backend
    container_name: inventory-worker-prod
    command: celery -A backend.worker:celery_app worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    networks:
      - inventory-network-prod

  frontend:
    build: ./frontend
    container_name: inventory-frontend-prod
    depends_on:
      - backend
    networks:
      - inventory-network-prod

  proxy:
    image: nginx:alpine
    container_name: inventory-proxy-prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - inventory-network-prod
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot
    container_name: inventory-certbot-prod
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data_prod:

networks:
  inventory-network-prod:
    driver: bridge
