version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: inventory-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-inventory_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure_password}
      POSTGRES_DB: ${POSTGRES_DB:-inventory_db}
    ports:
      - "5432:5432"
    networks:
      - inventory-network

  backend:
    build: ./backend
    container_name: inventory-backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-inventory_user}:${POSTGRES_PASSWORD:-secure_password}@db/${POSTGRES_DB:-inventory_db}
    depends_on:
      - db
    networks:
      - inventory-network

  frontend:
    build: ./frontend
    container_name: inventory-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - inventory-network

volumes:
  postgres_data:

networks:
  inventory-network:
    driver: bridge
