services:
  # 1. Servicio para el Backend (FastAPI + Alembic)
  - type: web
    name: hcg-backend
    env: docker
    # Asegúrate de que apunte a tu repositorio
    repo: https://github.com/almvfaa/hcg-data.git
    dockerfilePath: ./backend/Dockerfile
    # El comando de inicio ahora está en el Dockerfile (ENTRYPOINT ["/start.sh"])
    # por lo que la línea 'startCommand' se elimina.
    envVars:
      - key: DATABASE_URL
        # IMPORTANTE: Este valor lo debes pegar tú manualmente
        # en el dashboard de Render como un "Secret".
        # No lo pongas directamente aquí para mantenerlo seguro.
        value: "postgresql://inventory_user:DqHSpeLNX8O9qLTZdbmnyydPnfe754vm@dpg-d1ojuj49c44c73fnu3ig-a/inventory_db_iomh"
      - key: SECRET_KEY
        generateValue: true # Render generará un valor seguro
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 120
      - key: BACKEND_CORS_ORIGINS
        # Construimos la URL del frontend manualmente. Render usa el nombre del servicio.
        value: "https://hcg-frontend.onrender.com"

  # 2. Servicio para el Frontend (Next.js)
  - type: web
    name: hcg-frontend
    env: docker
    repo: https://github.com/almvfaa/hcg-data.git
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_API_URL
        # Construimos la URL del backend manualmente.
        value: "https://hcg-backend.onrender.com"
