// frontend/src/types/api.d.ts

/**
 * This file is automatically generated by 'openapi-typescript'.
 * Do not edit this file manually.
 * 
 * To update this file, first ensure your backend server is running,
 * then run the following command in the 'frontend' directory:
 * 
 * npm run generate-types
 */

// Example of what would be generated:
export interface paths {
  "/api/v1/catalogo/articulos": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": components["schemas"]["Articulo"][];
          };
        };
      };
    };
    post: {
        requestBody: {
            content: {
                "application/json": components["schemas"]["ArticuloCreate"];
            };
        };
        responses: {
            201: {
                content: {
                    "application/json": components["schemas"]["Articulo"];
                };
            };
        };
    };
  };
}

export interface components {
    schemas: {
        Articulo: {
            codigo_articulo: string;
            descripcion_articulo: string;
            unidad_medida?: string;
            partida_especifica: number;
        };
        ArticuloCreate: {
            codigo_articulo: string;
            descripcion_articulo: string;
            unidad_medida?: string;
            partida_especifica: number;
        };
    };
}
