"""Add indexes to core models

Revision ID: 1a2b3c4d5e6f
Revises: 
Create Date: 2023-10-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a2b3c4d5e6f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('CapitulosGasto',
    sa.Column('capitulo_gasto', sa.Integer(), nullable=False),
    sa.Column('denominacion_capitulo', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('capitulo_gasto')
    )
    op.create_index(op.f('ix_CapitulosGasto_capitulo_gasto'), 'CapitulosGasto', ['capitulo_gasto'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ConceptosGasto',
    sa.Column('concepto_gasto', sa.Integer(), nullable=False),
    sa.Column('denominacion_gasto', sa.String(length=255), nullable=False),
    sa.Column('capitulo_gasto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['capitulo_gasto'], ['CapitulosGasto.capitulo_gasto'], ),
    sa.PrimaryKeyConstraint('concepto_gasto')
    )
    op.create_index(op.f('ix_ConceptosGasto_capitulo_gasto'), 'ConceptosGasto', ['capitulo_gasto'], unique=False)
    op.create_index(op.f('ix_ConceptosGasto_concepto_gasto'), 'ConceptosGasto', ['concepto_gasto'], unique=False)
    op.create_table('PartidasGenericas',
    sa.Column('partida_generica', sa.Integer(), nullable=False),
    sa.Column('denominacion_partida_generica', sa.String(length=255), nullable=False),
    sa.Column('concepto_gasto', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concepto_gasto'], ['ConceptosGasto.concepto_gasto'], ),
    sa.PrimaryKeyConstraint('partida_generica')
    )
    op.create_index(op.f('ix_PartidasGenericas_concepto_gasto'), 'PartidasGenericas', ['concepto_gasto'], unique=False)
    op.create_index(op.f('ix_PartidasGenericas_partida_generica'), 'PartidasGenericas', ['partida_generica'], unique=False)
    op.create_table('PartidasEspecificas',
    sa.Column('partida_especifica', sa.Integer(), nullable=False),
    sa.Column('denominacion_partida_especifica', sa.String(length=255), nullable=False),
    sa.Column('partida_generica', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partida_generica'], ['PartidasGenericas.partida_generica'], ),
    sa.PrimaryKeyConstraint('partida_especifica')
    )
    op.create_index(op.f('ix_PartidasEspecificas_partida_generica'), 'PartidasEspecificas', ['partida_generica'], unique=False)
    op.create_index(op.f('ix_PartidasEspecificas_partida_especifica'), 'PartidasEspecificas', ['partida_especifica'], unique=False)
    op.create_table('Articulos',
    sa.Column('codigo_articulo', sa.String(length=50), nullable=False),
    sa.Column('descripcion_articulo', sa.String(), nullable=False),
    sa.Column('descripcion_larga_art', sa.String(), nullable=True),
    sa.Column('unidad_medida', sa.String(length=50), nullable=True),
    sa.Column('partida_especifica', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['partida_especifica'], ['PartidasEspecificas.partida_especifica'], ),
    sa.PrimaryKeyConstraint('codigo_articulo')
    )
    op.create_index(op.f('ix_Articulos_codigo_articulo'), 'Articulos', ['codigo_articulo'], unique=False)
    op.create_index(op.f('ix_Articulos_descripcion_articulo'), 'Articulos', ['descripcion_articulo'], unique=False)
    op.create_index(op.f('ix_Articulos_partida_especifica'), 'Articulos', ['partida_especifica'], unique=False)
    op.create_table('Movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('codigo_articulo', sa.String(length=50), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('tipo_movimiento', sa.Enum('ENTRADA', 'SALIDA', name='tipomovenum'), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('importe_total', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('precio_unitario_historico', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['codigo_articulo'], ['Articulos.codigo_articulo'], ),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_index('idx_movimiento_articulo_fecha', 'Movimientos', ['codigo_articulo', 'fecha'], unique=False)
    op.create_index(op.f('ix_Movimientos_codigo_articulo'), 'Movimientos', ['codigo_articulo'], unique=False)
    op.create_index(op.f('ix_Movimientos_fecha'), 'Movimientos', ['fecha'], unique=False)
    op.create_index(op.f('ix_Movimientos_id_movimiento'), 'Movimientos', ['id_movimiento'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Movimientos_id_movimiento'), table_name='Movimientos')
    op.drop_index(op.f('ix_Movimientos_fecha'), table_name='Movimientos')
    op.drop_index(op.f('ix_Movimientos_codigo_articulo'), table_name='Movimientos')
    op.drop_index('idx_movimiento_articulo_fecha', table_name='Movimientos')
    op.drop_table('Movimientos')
    op.drop_index(op.f('ix_Articulos_partida_especifica'), table_name='Articulos')
    op.drop_index(op.f('ix_Articulos_descripcion_articulo'), table_name='Articulos')
    op.drop_index(op.f('ix_Articulos_codigo_articulo'), table_name='Articulos')
    op.drop_table('Articulos')
    op.drop_index(op.f('ix_PartidasEspecificas_partida_especifica'), table_name='PartidasEspecificas')
    op.drop_index(op.f('ix_PartidasEspecificas_partida_generica'), table_name='PartidasEspecificas')
    op.drop_table('PartidasEspecificas')
    op.drop_index(op.f('ix_PartidasGenericas_partida_generica'), table_name='PartidasGenericas')
    op.drop_index(op.f('ix_PartidasGenericas_concepto_gasto'), table_name='PartidasGenericas')
    op.drop_table('PartidasGenericas')
    op.drop_index(op.f('ix_ConceptosGasto_concepto_gasto'), table_name='ConceptosGasto')
    op.drop_index(op.f('ix_ConceptosGasto_capitulo_gasto'), table_name='ConceptosGasto')
    op.drop_table('ConceptosGasto')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_CapitulosGasto_capitulo_gasto'), table_name='CapitulosGasto')
    op.drop_table('CapitulosGasto')
    # ### end Alembic commands ###
