# .github/workflows/backend-ci.yml
name: Backend CI & Quality Assurance

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Run Quality Checks
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend # Set the working directory for all run steps

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        # Cache pip dependencies for faster builds
        cache: 'pip'
        cache-dependency-path: 'backend/requirements-dev.txt'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Install both production and development dependencies
        pip install -r requirements-dev.txt

    - name: Check Formatting with Black
      run: |
        echo "Running Black..."
        black . --check
    
    - name: Lint with Flake8
      run: |
        echo "Running Flake8..."
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with Pytest
      run: |
        echo "Running Pytest..."
        pytest
